# start this container with:
#docker run -it --rm --privileged --name my-router --cap-add=NET_ADMIN --network=host -e "WAN_IF=enp2s0" -e "LAN_IF=enp3s0" -e "VLAN_ID=7" -e "PPPOE_USERNAME=<redacted>" -e "PPPOE_PASSWORD=<redacted>" localhost/router

FROM docker.io/alpine:3.23.3

RUN apk add --no-cache \
  rp-pppoe \
  ppp \
  dnsmasq \
  iptables \
  ip6tables \
  procps-ng \
  iproute2

# Add build-time argument for enabling IPv6
ARG ENABLE_IPV6=true
# Set environment variable from build-time argument
ENV ENABLE_IPV6=$ENABLE_IPV6

# Set environment variables for PPPoE credentials (to be passed at runtime)
# These are default values and should be overridden.
ENV PPPOE_USERNAME="YOUR_PPPOE_USERNAME"
ENV PPPOE_PASSWORD="YOUR_PPPOE_PASSWORD"

# Create the entrypoint script using a heredoc and set executable permissions in one step.
# NOTE: Quoted 'ENTRYPOINT' to prevent shell variable expansion at build time.
# This ensures variables are evaluated at runtime inside the container.
COPY --chmod=0755 <<'ENTRYPOINT' /entrypoint.sh
#!/bin/sh
# Exit immediately if a command exits with a non-zero status.
set -ex

# --- Cleanup from previous runs ---
echo ">> Stopping any existing PPPoE connection..."
killall pppd || true
echo ">> Stopping any existing dnsmasq process..."
killall dnsmasq || true
sleep 1

# --- Configuration ---
# Use environment variables with defaults.
# These can be overridden with `docker run -e ...`
WAN_IF="${WAN_IF:-enp2s0}"
LAN_IF="${LAN_IF:-eno1}"
LAN_IP="${LAN_IP:-192.168.50.1}"
DHCP_RANGE_START="${DHCP_RANGE_START:-192.168.50.50}"
DHCP_RANGE_END="${DHCP_RANGE_END:-192.168.50.150}"
LAN_SUBNET_CIDR=$(echo "$LAN_IP" | cut -d'.' -f1-3).0/24 # Automatically calculate subnet
VLAN_ID="${VLAN_ID}" # Set to "" or unset to disable. Example: 7

# --- Dynamic Configuration Generation ---
echo ">> Generating dnsmasq configuration for interface ${LAN_IF}..."
cat > /etc/dnsmasq.conf <<EOF
# Configuration generated by entrypoint.sh
# Listen on the LAN interface
interface=${LAN_IF}
# Do not act as a DNS server, only DHCP
port=0
# Define the DHCP range, lease time, and router/DNS options
dhcp-range=${DHCP_RANGE_START},${DHCP_RANGE_END},12h
dhcp-option=option:router,${LAN_IP}
dhcp-option=option:dns-server,208.67.222.222,208.67.220.220
# Enable DHCP logging
log-dhcp
EOF

echo ">> Configuring PPPoE credentials for PAP..."
# Create the pap-secrets file required by pppd for PAP authentication
echo "\"\"$PPPOE_USERNAME\"\" * \"\"$PPPOE_PASSWORD\"\" *" > /etc/ppp/pap-secrets
chmod 600 /etc/ppp/pap-secrets

# --- VLAN Setup (if VLAN_ID is specified) ---
if [ -n "$VLAN_ID" ]; then
echo ">> Configuring VLAN ${VLAN_ID} on ${WAN_IF}..."
# modprobe 8021q

VLAN_IF_TAGGED="${WAN_IF}.${VLAN_ID}"
if ! ip link show "${VLAN_IF_TAGGED}" > /dev/null 2>&1; then
    ip link add link "${WAN_IF}" name "${VLAN_IF_TAGGED}" type vlan id "${VLAN_ID}"
fi
ip link set "${VLAN_IF_TAGGED}" up

# Update WAN_IF to use the new tagged interface for PPPoE
WAN_IF="${VLAN_IF_TAGGED}"
echo ">> WAN interface is now ${WAN_IF}"
fi

echo ">> Generating pppd configuration..."
mkdir -p /etc/ppp/peers

PPPD_IPV6_OPTION=""
if [ "$ENABLE_IPV6" = "false" ]; then
  PPPD_IPV6_OPTION="noipv6"
else
  PPPD_IPV6_OPTION="+ipv6"
fi

cat > /etc/ppp/peers/dsl-provider <<EOF
# Configuration generated by entrypoint.sh
plugin /etc/ppp/plugins/rp-pppoe.so
nic-${WAN_IF}
user "${PPPOE_USERNAME}"
${PPPD_IPV6_OPTION}
noipdefault
defaultroute
replacedefaultroute
usepeerdns
persist
nodetach
# T-Online specific settings
refuse-chap
refuse-mschap
refuse-mschap-v2
noaccomp
nodeflate
nopcomp
novj
noccp
lcp-echo-interval 10
lcp-echo-failure 4
debug
dump
EOF

echo ">> Enabling IP forwarding..."
sysctl -w net.ipv4.ip_forward=1

if [ "$ENABLE_IPV6" = "true" ]; then
  echo ">> Enabling IPv6 forwarding..."
  sysctl -w net.ipv6.conf.all.forwarding=1
  sysctl -w net.ipv6.conf.default.forwarding=1
fi


echo ">> Flushing existing iptables rules..."
iptables -F
iptables -t nat -F
iptables -t mangle -F

if [ "$ENABLE_IPV6" = "true" ]; then
    echo ">> Flushing existing ip6tables rules..."
    ip6tables -F || true
    ip6tables -t nat -F || true
    ip6tables -t mangle -F || true
fi


echo ">> Creating ip-up script for pppd..."
cat > /etc/ppp/ip-up <<EOF
#!/bin/sh
# This script is executed when the ppp connection is established.
# $1 is the interface name, e.g. ppp0

echo "ip-up script called for \$1" >> /tmp/ip-up.log

/usr/sbin/iptables -A FORWARD -i "${LAN_IF}" -o \$1 -j ACCEPT
/usr/sbin/iptables -A FORWARD -i \$1 -o "${LAN_IF}" -m state --state RELATED,ESTABLISHED -j ACCEPT
/usr/sbin/iptables -t nat -A POSTROUTING -s "${LAN_SUBNET_CIDR}" -o \$1 -j MASQUERADE
if [ "$ENABLE_IPV6" = "true" ]; then
    /usr/sbin/ip6tables -A FORWARD -i "${LAN_IF}" -o \$1 -j ACCEPT
    /usr/sbin/ip6tables -A FORWARD -i \$1 -o "${LAN_IF}" -m state --state RELATED,ESTABLISHED -j ACCEPT
fi
EOF
chmod +x /etc/ppp/ip-up

# The host machine needs to have an IP on the LAN interface for dnsmasq to bind to.
# Let's ensure the LAN_IF is up and has the correct IP.
echo ">> Configuring LAN interface ${LAN_IF} with IP ${LAN_IP}..."
if ! ip a show dev "${LAN_IF}" | grep -q "inet ${LAN_IP}"; then
  ip addr add "${LAN_IP}/24" dev "${LAN_IF}"
fi
ip link set "${LAN_IF}" up

echo ">> Starting dnsmasq DHCP server on ${LAN_IF}..."
dnsmasq -k &

echo ">> Starting PPPoE connection on ${WAN_IF}..."
exec pppd call dsl-provider

ENTRYPOINT

# Set the entrypoint for the container
ENTRYPOINT ["/entrypoint.sh"]
